Edit make action_hw
Signed-off-by: Lu Yong <luyong@cn.ibm.com>

diff --git a/hardware/Makefile b/hardware/Makefile
--- a/hardware/Makefile
+++ b/hardware/Makefile
@@ -48,6 +48,7 @@ SIM_DIR=$(OCACCEL_HARDWARE_ROOT)/sim
 
 BUILD_DIR=$(OCACCEL_HARDWARE_ROOT)/build
 IP_REPO_DIR=$(BUILD_DIR)/ip_repo
+IP_REPO_USER_DIR=$(BUILD_DIR)/ip_user_repo
 INTERFACES_DIR=$(BUILD_DIR)/interfaces
 VIV_PROJ_DIR=$(BUILD_DIR)/viv_project
 
@@ -63,7 +64,7 @@ COMMON_SCRIPT_SRCS  += $(shell find $(SCRIPT_ROOT)/create_framework       -name 
 HOST_SCRIPT_SRCS    := $(shell find $(SCRIPT_ROOT)/package_hostside       -name "*.tcl" -or -name "*.sh")
 INFRA_SCRIPT_SRCS   := $(shell find $(SCRIPT_ROOT)/package_infrastructure -name "*.tcl" -or -name "*.sh")
 SIM_SCRIPT_SRCS     := $(shell find $(SCRIPT_ROOT)/simulation             -name "*.tcl" -or -name "*.sh")
-ACTION_SCRIPT_SRCS  := $(shell find $(SCRIPT_ROOT)/simulation             -name "*.tcl" -or -name "*.sh")
+ACTION_SCRIPT_SRCS  := $(shell find $(SCRIPT_ROOT)/package_action         -name "*.tcl" -or -name "*.sh")
 
 OCACCEL_SIMULATORS += xsim xcelium
 templog=/dev/null
@@ -128,12 +129,14 @@ check_ocaccel_settings:
 	@echo "                        CAPI_VERSION    = $(CAPI_VER)"
 	@echo "                        FPGACARD        = $(FPGACARD)"
 	@echo "                        FPGACHIP        = $(FPGACHIP)"
-	@echo "                        PHY_SPEED       = $(PHY_SPEED)"
 	@echo "                        INFRA_TEMPLATE  = $(INFRA_TEMPLATE_SELECTION)"
 	@echo "                        ACTION_TEMPLATE = $(ACTION_TEMPLATE_SELECTION)"
+	@echo "                        KERNEL_NUMBER   = $(KERNEL_NUMBER)"
+	@echo "                        ACTION_FREQUENCY= $(ACTION_CLOCK_FREQUENCY)"
+	@echo "                        PHY_SPEED       = $(PHY_SPEED)"
 	@echo "                        ILA_DEBUG       = $(ILA_DEBUG)"
-	@echo "                        FLASH_INTERFACE = $(FLASH_INTERFACE)"
-	@echo "                        FLASH_SIZE      = $(FLASH_SIZE)"
+#	@echo "                        FLASH_INTERFACE = $(FLASH_INTERFACE)"
+#	@echo "                        FLASH_SIZE      = $(FLASH_SIZE)"
 	@if [ `echo "$(ILA_DEBUG)" | tr a-z A-Z` == "TRUE" ]; then \
 		echo "                        ILA_SETUP_FILE  = $(ILA_SETUP_FILE)"; \
 	fi
@@ -192,26 +195,6 @@ ocaccel_preprocess_execute: $(OCACCEL_PREPROCESS_FILES)
 ocaccel_preprocess: ocaccel_preprocess_start
 	@$(MAKE) -s ocaccel_preprocess_execute
 
-###############################################################################
-
-action_hw: prepare_logs
-	@echo -e "[CONFIG ACTION HW....] start `date +"%T %a %b %d %Y"`";
-	@if [ ! -d "$(ACTION_ROOT)" ]; then \
-		echo "                        Error: Path to ACTION_ROOT is not defined properly"; exit -1; \
-	fi
-	@echo "Calling make -C $(ACTION_ROOT) hw" > $(LOGS_DIR)/action_make.log
-	@$(MAKE) -C $(ACTION_ROOT) hw >> $(LOGS_DIR)/action_make.log;
-	@if [ $$? -ne 0 ]; then \
-		echo -e "                        Error: please look into $(LOGS_DIR)/action_make.log"; exit -1; \
-	fi
-	@if [ "$(HLS_SUPPORT)" == "TRUE" ]; then \
-	        echo "Calling make -C $(ACTION_ROOT)/hw " >> $(LOGS_DIR)/action_make.log; \
-		$(MAKE) -kC $(ACTION_ROOT)/hw  >> $(LOGS_DIR)/action_make.log; \
-		if [ $$? -ne 0 ]; then \
-			echo -e "                        Error: please look into $(LOGS_DIR)/action_make.log"; exit -1; \
-		fi; \
-	fi
-	@echo -e "[CONFIG ACTION HW....] done  `date +"%T %a %b %d %Y"`";
 
 ###############################################################################
 # Build the vivado project
@@ -231,6 +214,31 @@ package_infrastructure: $(INFRA_VERILOG_SRCS) $(COMMON_VERILOG_SRCS) $(INFRA_SCR
 #	@cd $(BUILD_DIR) &&  vivado -quiet -mode batch -source $(SETUP_DIR)/package_infrastructure/bd_infra_template_$(INFRA_TEMPLATE_SELECTION).tcl -notrace -log $(LOGS_DIR)/bd_infra_template_$(INFRA_TEMPLATE_SELECTION).log -journal $(LOGS_DIR)/bd_infra_template_$(INFRA_TEMPLATE_SELECTION).jou > $(templog)
 	@echo -e "[PACKAGE INFRA.......] done  `date +"%T %a %b %d %Y"`";
 
+###############################################################################
+action_hw: prepare_logs
+	@echo -e "[CONFIG ACTION HW....] start `date +"%T %a %b %d %Y"`";
+	@if [ ! -d "$(ACTION_ROOT)" ]; then \
+		echo "                        Error: Path to ACTION_ROOT is not defined properly"; exit -1; \
+	fi
+#	@echo "Calling make -C $(ACTION_ROOT) hw " > $(LOGS_DIR)/action_make.log
+#	@$(MAKE) -C $(ACTION_ROOT) hw >> $(LOGS_DIR)/action_make.log;
+#	@if [ $$? -ne 0 ]; then \
+#		echo -e "                        Error: please look into $(LOGS_DIR)/action_make.log"; exit -1; \
+#	fi
+	@if [ "$(HLS_SUPPORT)" == "TRUE" ]; then \
+	    echo "Calling make -C $(ACTION_ROOT)/hw " >> $(LOGS_DIR)/action_make.log; \
+		$(MAKE) -kC $(ACTION_ROOT)/hw  >> $(LOGS_DIR)/action_make.log; \
+		if [ $$? -ne 0 ]; then \
+			echo -e "                        Error: please look into $(LOGS_DIR)/action_make.log"; exit -1; \
+		fi; \
+    else \
+        echo "Package user written HDL design to an IP" >> $(LOGS_DIR)/action_make.log; \
+      	cd $(BUILD_DIR); \
+        vivado -quiet -mode batch -source $(SETUP_DIR)/package_action/package_hdl_kernel.tcl -notrace -log $(LOGS_DIR)/package_hdl_kernel.log -journal $(LOGS_DIR)/package_hdl_kernel.jou > $(templog); \
+    fi;
+	@echo -e "[CONFIG ACTION HW....] done  `date +"%T %a %b %d %Y"`";
+
+###############################################################################
 #package_action: $(ACTION_SCRIPT_SRCS)
 #	@echo -e "[PACKAGE ACTION......] start `date +"%T %a %b %d %Y"`";
 #	@cd $(BUILD_DIR) &&  vivado -quiet -mode batch -source $(SETUP_DIR)/package_action/package_action_wrapper.tcl -notrace -log $(LOGS_DIR)/package_action_wrapper.log -journal $(LOGS_DIR)/package_action_wrapper.jou > $(templog)
@@ -242,7 +250,7 @@ top_project: $(COMMON_VERILOG_SRCS) $(COMMON_VERILOG_SRCS)
 	@cd $(BUILD_DIR)  &&  vivado -quiet -mode batch -source $(SETUP_DIR)/create_framework/create_top_$(INFRA_TEMPLATE_SELECTION).tcl -notrace -log $(LOGS_DIR)/create_top_$(INFRA_TEMPLATE_SELECTION).log  -journal $(LOGS_DIR)/create_top_$(INFRA_TEMPLATE_SELECTION).jou > $(templog)
 	@echo -e "[CREATE TOP PROJECT..] done  `date +"%T %a %b %d %Y"`"
 
-hw_project: ocaccel_preprocess action_hw define_interfaces package_hostside package_infrastructure top_project
+hw_project: ocaccel_preprocess define_interfaces package_hostside package_infrastructure action_hw top_project
 	@echo -e "                       using `vivado -version |grep Vivado`"
 	@echo -e "                       CAPI_VER=$(CAPI_VER)"
 	@echo -e "[HW PROJECT]           done  `date +"%T %a %b %d %Y"`"
