Added -t option

diff --git a/software/tools/oc_find_card b/software/tools/oc_find_card
--- a/software/tools/oc_find_card
+++ b/software/tools/oc_find_card
@@ -39,6 +39,7 @@ function usage() {
 	echo "    [-v] Prints extra information (to be put as first param)"
 	echo "    [-A] <accelerator> use either ADKU3, N250S, S121B_BPIx16, S121B_SPIx4, AD8K5, RCXVUP, FX609, S241, N250SP, AD9V3, OC-AD9V3, AD9H3, OC-AD9H3, AD9H7, OC-AD9H7, U200 or ALL"
 	echo "    [-C] <0..3> Print accelerator name for this Card"
+	echo "    [-t] <1..3> Specifies the Type of CAPI: CAPI1.0, CAPI2.0 or OPENCAPI (CAPI3.0)"
 	echo "    [-V] provides version"
 	echo "  prints out a list of CAPI Cards found in this System."
 	echo
@@ -261,7 +262,9 @@ function detect_oc_card_name()
 # Main Start here
 # Parse any options given on the command line
 PROGRAM=$0
-while getopts ":vA:C:Vh" opt; do
+card=""
+type=""
+while getopts ":vA:C:Vht:" opt; do
 	case ${opt} in
 	v)
 		VERBOSE=1
@@ -272,81 +275,9 @@ while getopts ":vA:C:Vh" opt; do
 		;;
 	C)
 		card=${OPTARG};
-		rc=0
-		if [[ $card -gt 3 ]]; then
-			echo "Invalid option for -C -$OPTARG" >&2
-			usage
-			exit 0
-		fi
-		detect_card_name $card  "0x0632" "0x0605" "ADKU3"
-		if [ $? == 1 ]; then
-			rc=1
-		fi
-		detect_card_name $card  "0x0632" "0x060a" "N250S"
-		if [ $? == 1 ]; then
-			rc=1
-		fi
-		detect_card_name $card  "0x0632" "0x0607" "S121B_v16.1_BPIx16"
-		if [ $? == 1 ]; then
-			rc=1
-		fi
-		detect_card_name $card  "0x0632" "0x0664" "S121B_v16.2_SPIx4"
-		if [ $? == 1 ]; then
-			rc=1
-		fi
-		detect_card_name $card  "0x0632" "0x060c" "RCXVUP"
-		if [ $? == 1 ]; then
-			rc=1
-		fi
-		detect_card_name $card  "0x0632" "0x060d" "N250SP"
-		if [ $? == 1 ]; then
-			rc=1
-		fi
-		detect_card_name $card  "0x0632" "0x0661" "FX609"
-		if [ $? == 1 ]; then
-			rc=1
-		fi
-		detect_card_name $card  "0x0632" "0x0660" "S241"
-		if [ $? == 1 ]; then
-			rc=1
-		fi
-		detect_card_name $card  "0x0632" "0x0608" "AD8K5"
-		if [ $? == 1 ]; then
-			rc=1
-		fi
-		detect_card_name $card  "0x0632" "0x04dd" "N250SP"
-		if [ $? == 1 ]; then
-			rc=1
-		fi
-		detect_card_name $card  "0x0632" "0x060f" "AD9V3"
-		if [ $? == 1 ]; then
-			rc=1
-		fi
-		detect_card_name $card  "0x0632" "0x0667" "AD9H3"
-		if [ $? == 1 ]; then
-			rc=1
-		fi
-		detect_card_name $card  "0x0632" "0x0665" "U200"
-		if [ $? == 1 ]; then
-			rc=1
-		fi
-		detect_card_name $card  "0x0602" "" "GZIP"
-		if [ $? == 1 ]; then
-			rc=1
-		fi
-		detect_oc_card_name $card  "0x062b" "0x060f" "OC-AD9V3"
-                if [ $? == 1 ]; then
-                        rc=1
-                fi
-		detect_oc_card_name $card  "0x062b" "0x0667" "OC-AD9H3"
-		 if [ $? == 1 ]; then
-		        rc=1
-		fi
-                detect_oc_card_name $card  "0x062b" "0x0666" "OC-AD9H7"
-                 if [ $? == 1 ]; then
-                        rc=1
-                fi
-		exit $rc
+		;;
+	t)
+		type=${OPTARG}
 		;;
 	V)
 		echo "${version}" >&2
@@ -369,6 +300,85 @@ done
 
 shift $((OPTIND-1))
 # now do something with $@
+
+if  ["$card" != ""]; then
+  	rc=0
+	if [[ $card -gt 3 ]]; then
+		echo "Invalid option for -C -$OPTARG" >&2
+		usage
+		exit 0
+	fi
+	detect_card_name $card  "0x0632" "0x0605" "ADKU3"
+	if [ $? == 1 ]; then
+		rc=1
+	fi
+	detect_card_name $card  "0x0632" "0x060a" "N250S"
+	if [ $? == 1 ]; then
+		rc=1
+	fi
+	detect_card_name $card  "0x0632" "0x0607" "S121B_v16.1_BPIx16"
+	if [ $? == 1 ]; then
+		rc=1
+	fi
+	detect_card_name $card  "0x0632" "0x0664" "S121B_v16.2_SPIx4"
+	if [ $? == 1 ]; then
+		rc=1
+	fi
+	detect_card_name $card  "0x0632" "0x060c" "RCXVUP"
+	if [ $? == 1 ]; then
+		rc=1
+	fi
+	detect_card_name $card  "0x0632" "0x060d" "N250SP"
+	if [ $? == 1 ]; then
+		rc=1
+	fi
+	detect_card_name $card  "0x0632" "0x0661" "FX609"
+	if [ $? == 1 ]; then
+		rc=1
+	fi
+	detect_card_name $card  "0x0632" "0x0660" "S241"
+	if [ $? == 1 ]; then
+		rc=1
+	fi
+	detect_card_name $card  "0x0632" "0x0608" "AD8K5"
+	if [ $? == 1 ]; then
+		rc=1
+	fi
+	detect_card_name $card  "0x0632" "0x04dd" "N250SP"
+	if [ $? == 1 ]; then
+		rc=1
+	fi
+	detect_card_name $card  "0x0632" "0x060f" "AD9V3"
+	if [ $? == 1 ]; then
+		rc=1
+	fi
+	detect_card_name $card  "0x0632" "0x0667" "AD9H3"
+	if [ $? == 1 ]; then
+		rc=1
+	fi
+	detect_card_name $card  "0x0632" "0x0665" "U200"
+	if [ $? == 1 ]; then
+		rc=1
+	fi
+	detect_card_name $card  "0x0602" "" "GZIP"
+	if [ $? == 1 ]; then
+		rc=1
+	fi
+	detect_oc_card_name $card  "0x062b" "0x060f" "OC-AD9V3"
+    if [ $? == 1 ]; then
+        rc=1
+    fi
+	detect_oc_card_name $card  "0x062b" "0x0667" "OC-AD9H3"
+	 if [ $? == 1 ]; then
+        rc=1
+	fi
+    detect_oc_card_name $card  "0x062b" "0x0666" "OC-AD9H7"
+        if [ $? == 1 ]; then
+            rc=1
+        fi
+	exit $rc
+fi
+
 RC=0
 
 case ${accel} in
